### ISSUE TITLE
问下你这个项目如何执行？

### ISSUE THREAD

**Issue by ggchxx** [totzcc/WeexHTMLParse#1]
问下你这个项目如何执行？

**Comment by ggchxx** [comment]
npm run serve & weexpack run web 都试了不行呢

**Comment by totzcc** [comment]
```
npm run dev
```

**Comment by caozhiyong** [comment]
[67] ./src/more.vue?entry=true 1.71 kB {1} [built]
  [68] ./src/my-info.vue?entry=true 1.48 kB {7} [built]
  [69] ./src/my.vue?entry=true 1.7 kB {13} [built]
    + 61 hidden modules

npm run dev 运行到这里就过不去了，是什么原因呢

**Comment by totzcc** [comment]
@caozhiyong 这是已经编译结束了。你可以开始运行iOS项目

**Comment by shimangdian** [comment]
npm run dev:web 不行呢？

**Comment by totzcc** [comment]
@shimangdian 因为里面用到了解析HTML 的第三方框架。所以不支持Web, 现在只有iOS和Android
