### ISSUE TITLE
上架问题

### ISSUE THREAD

**Issue by aoping** [totzcc/WeexHTMLParse#5]
最后是怎么解决上架问题的？

**Comment by totzcc** [comment]
iOS的安装包里面内置一个zip包。让首次安装无网络的人也能用。

**Comment by aoping** [comment]
我的意思是怎么过审核的

**Comment by totzcc** [comment]
提交审核就能过啊。Weex 的App能通过审核

我之前没能通过审核的原因是因为我的bundle js文件是在线的。苹果的审核人员在美国。访问的时候首屏加载速度可能特别慢。就给我拒绝了。 你遇到了什么问题？

**Comment by totzcc** [comment]
长时间未回复，关闭 issue
