### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by zhuchaoming** [totzcc/WeexHTMLParse#8]
按照文档运行项目，页面只是列出了文件列表

**Comment by totzcc** [comment]
项目只支持iOS和Android， 不支持H5

**Comment by zhuchaoming** [comment]
windows 下在 Git bash中切换到项目下，运行 cnpm install 和 ./start，浏览器访问还是显示文件列表。开了Android模拟机，也没反应。也不安装到模拟机上面

**Comment by totzcc** [comment]
哥哥诶。说了不支持H5 ，就是说不支持浏览器访问哦，你需要运行Android 或者 iOS 的客户端。 Debug模式下。修改bundle js的主机地址
